[package]
name = "stratisd"
version = "3.5.0"
authors = ["Stratis Developers <stratis-devel@lists.fedorahosted.org>"]
edition = "2021"
rust-version = "1.62.1"  # LOWEST SUPPORTED RUST TOOLCHAIN
build = "build.rs"
description = "Stratis daemon"
license-file = "LICENSE"
repository = "https://github.com/stratis-storage/stratisd/"
keywords = ["Linux", "filesystem", "storage"]
categories = ["filesystem"]
exclude = [
    "docs",
    "dracut",
    ".clippy.toml",
    ".gitignore",
    ".githooks/*",
    ".github/*",
    "systemd",
    "tests",
    "udev",
    "Makefile",
    "README_tests.md",
    "stratisd.conf"
]

[[bin]]
name = "stratis-dumpmetadata"
required-features = ["extras", "min"]

[[bin]]
name = "stratis-min"
path = "src/bin/stratis-min/stratis-min.rs"
required-features = ["min"]

[[bin]]
name = "stratisd-min"
path = "src/bin/stratis-min/stratisd-min.rs"
required-features = ["min"]

[[bin]]
name = "stratis-utils"

[dependencies.async-trait]
version = "0.1.51"

[dependencies.byteorder]
version = "1.2.3"

[dependencies.chrono]
version = "0.4.20"
default-features = false
features = ["clock", "std"]

[dependencies.clap]
version = "3.1.9"

[dependencies.crc]
version = "2.0.0"

[dependencies.crossbeam]
version = "0.8.0"

[dependencies.data-encoding]
version = "2.3.0"

[dependencies.devicemapper]
version = "0.32.3"

[dependencies.dbus]
version = "0.9.0"
features = ["futures"]
optional = true

[dependencies.dbus-tree]
version = "0.9.2"
optional = true

[dependencies.either]
version = "1.6.1"

[dependencies.env_logger]
version ="0.9.0"

[dependencies.futures]
version = "0.3.11"

[dependencies.iocuddle]
version = "0.1.0"

[dependencies.itertools]
version = "0.10.1"

[dependencies.lazy_static]
version = "1.4.0"

[dependencies.libblkid-rs]
version = "0.2.0"

[dependencies.libc]
version = "0.2.121"

[dependencies.libcryptsetup-rs]
version = "0.6.0"
features = ["mutex"]

[dependencies.libmount]
version = "0.1.9"

[dependencies.libudev]
version = "0.3.0"

[dependencies.log]
version = "0.4.14"

[dependencies.nix]
version = "0.24.0"

[dependencies.pretty-hex]
version = "0.3.0"
optional = true

[dependencies.rand]
version = "0.8.0"

[dependencies.regex]
version = "1.5.4"

[dependencies.retry]
version = "1.3.1"

[dependencies.rpassword]
version = "5.0.0"
optional = true

[dependencies.serde]
version = "1.0.119"

[dependencies.serde_derive]
version = "1.0.119"

[dependencies.serde_json]
version = "1.0.50"

[dependencies.sha2]
version = "0.10.1"

[dependencies.stratisd_proc_macros]
version = "0.1.0"
path = "./stratisd_proc_macros"

[dependencies.tempfile]
version = "3.0.2"

[dependencies.tokio]
version = "1.5.0"
features = ["sync", "macros", "rt", "rt-multi-thread", "signal", "net", "time"]

[dependencies.uuid]
version = "1.0.0"
features = ["serde", "v4"]

[build-dependencies]
pkg-config = "0.3.18"

[build-dependencies.bindgen]
default_features = false
features = ["runtime"]
version = "0.63.0"
optional = true

[dev-dependencies]
assert_matches = "1.5.0"
loopdev = "0.4.0"
proptest = "1.0.0"

[features]
default = ["dbus_enabled"]
dbus_enabled = ["dbus", "dbus-tree"]
extras = ["pretty-hex"]
min = ["rpassword"]
systemd_compat = ["bindgen"]
