---
name: stratisd CI

# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - master
      - develop-2.4.1
    paths-ignore:
      - 'CHANGES.txt'
      - '**/README.md'
  pull_request:
    branches:
      - master
      - develop-2.4.1
    paths-ignore:
      - 'CHANGES.txt'
      - '**/README.md'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  checks:
    strategy:
      matrix:
        include:
          # MANDATORY CHECKS USING CURRENT DEVELOPMENT COMPILER
          - task: make -f Makefile fmt-travis
            toolchain: 1.51.0
            components: rustfmt
            image: ubuntu:groovy
          - task: make -f Makefile clippy
            toolchain: 1.51.0
            components: clippy
            image: ubuntu:groovy
          - task: make -f Makefile fmt-travis
            toolchain: 1.51.0
            components: rustfmt
            image: fedora:32
          - task: make -f Makefile clippy
            toolchain: 1.51.0
            components: clippy
            image: fedora:32
          # MANDATORY TESTING ON STABLE
          - task: make -f Makefile build
            toolchain: stable
            components: cargo
            image: ubuntu:groovy
          - task: make -f Makefile build-min
            toolchain: stable
            components: cargo
            image: ubuntu:groovy
          - task: make -f Makefile build-extras
            toolchain: stable
            components: cargo
            image: ubuntu:groovy
          - task: make -f Makefile docs-travis
            toolchain: stable
            components: cargo
            image: ubuntu:groovy
          - task: make -f Makefile test
            toolchain: stable
            components: cargo
            image: ubuntu:groovy
          - task: make -f Makefile release
            toolchain: stable
            components: cargo
            image: ubuntu:groovy
          - task: make -f Makefile release-min
            toolchain: stable
            components: cargo
            image: ubuntu:groovy
          - task: make -f Makefile build
            toolchain: stable
            components: cargo
            image: fedora:32
          - task: make -f Makefile build-min
            toolchain: stable
            components: cargo
            image: fedora:32
          - task: make -f Makefile build-extras
            toolchain: stable
            components: cargo
            image: fedora:32
          - task: make -f Makefile docs-travis
            toolchain: stable
            components: cargo
            image: fedora:32
          - task: make -f Makefile test
            toolchain: stable
            components: cargo
            image: fedora:32
          - task: make -f Makefile release
            toolchain: stable
            components: cargo
            image: fedora:32
          - task: make -f Makefile release-min
            toolchain: stable
            components: cargo
            image: fedora:32
    runs-on: ubuntu-18.04
    container:
      image: ${{ matrix.image }}
      options: --privileged -v /dev:/dev
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies for Ubuntu
        run: apt-get -q update
        if: matrix.image == 'ubuntu:groovy'
      - name: Install dependencies for Ubuntu
        run: >
          DEBIAN_FRONTEND=noninteractive
          apt-get install -y
          clang
          curl
          libblkid-dev
          libcryptsetup-dev
          libdbus-1-dev
          libsystemd-dev
          libudev-dev
          make
        if: matrix.image == 'ubuntu:groovy'
      - name: Install dependencies for Fedora
        run: >
          dnf install -y
          clang
          curl
          cryptsetup-devel
          dbus-devel
          libblkid-devel
          make
          systemd-devel
        if: matrix.image == 'fedora:32'
      - uses: actions-rs/toolchain@v1
        with:
          components: ${{ matrix.components }}
          toolchain: ${{ matrix.toolchain }}
          override: true
      - name: Test ${{ matrix.task }} on ${{ matrix.toolchain }} toolchain
        run: ${{ matrix.task }}

  # TESTS WITH UDEV
  checks_with_udev:
    strategy:
      matrix:
        include:
          # MANDATORY CHECKS USING CURRENT DEVELOPMENT COMPILER
          - task: RUST_LOG=libstratis=debug make -f Makefile test-loop
            toolchain: stable
            components: cargo
            image: ubuntu:groovy
          - task: RUST_LOG=libstratis=debug make -f Makefile test-loop
            toolchain: stable
            components: cargo
            image: fedora:32
    runs-on: ubuntu-18.04
    container:
      image: ${{ matrix.image }}
      options: --privileged -v /dev:/dev
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies for Ubuntu
        run: apt-get -q update
        if: matrix.image == 'ubuntu:groovy'
      - name: Install dependencies for Ubuntu
        run: >
          DEBIAN_FRONTEND=noninteractive
          apt-get install -y
          asciidoc
          clang
          curl
          libblkid-dev
          libcryptsetup-dev
          libdbus-1-dev
          libsystemd-dev
          libudev-dev
          make
          systemd
          thin-provisioning-tools
          udev
          xfsprogs
        if: matrix.image == 'ubuntu:groovy'
      - name: Install dependencies for Fedora
        run: >
          dnf install -y
          asciidoc
          clang
          cryptsetup-devel
          curl
          device-mapper-persistent-data
          dbus-devel
          libblkid-devel
          make
          systemd-devel
          systemd-udev
          xfsprogs
        if: matrix.image == 'fedora:32'
      - uses: actions-rs/toolchain@v1
        with:
          components: ${{ matrix.components }}
          toolchain: ${{ matrix.toolchain }}
          override: true
      - name: Install all necessary Stratis files
        run: make install
      - name: Start udev
        run: /usr/lib/systemd/systemd-udevd &
      - name: Test ${{ matrix.task }} on ${{ matrix.toolchain }} toolchain
        run: ${{ matrix.task }}

  # TESTS WITH TANG
  checks_with_tang:
    strategy:
      matrix:
        include:
          # MANDATORY CHECKS USING CURRENT DEVELOPMENT COMPILER
          - task: >-
              TANG_URL=tang
              RUST_LOG=libstratis=debug
              make -f Makefile test-clevis-loop
            toolchain: stable
            components: cargo
            image: fedora:32
    runs-on: ubuntu-18.04
    container:
      image: ${{ matrix.image }}
      options: --privileged -v /dev:/dev
    services:
      tang:
        image: docker.pkg.github.com/stratis-storage/stratisd/tang:32
        credentials:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
        options: --privileged -p 80:80
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies for Fedora
        run: >
          dnf install -y
          clang
          cryptsetup-devel
          clevis
          clevis-luks
          curl
          device-mapper-persistent-data
          dbus-devel
          libblkid-devel
          make
          systemd-devel
          systemd-udev
          xfsprogs
      - name: Start udev
        run: /usr/lib/systemd/systemd-udevd &
      - uses: actions-rs/toolchain@v1
        with:
          components: ${{ matrix.components }}
          toolchain: ${{ matrix.toolchain }}
          override: true
      - name: Test ${{ matrix.task }} on ${{ matrix.toolchain }} toolchain
        run: ${{ matrix.task }}

  python-checks:
    strategy:
      matrix:
        include:
          # PYTHON CHECKS ON CURRENT FEDORA AND PYTHON TOOLS VERSION
          - dependencies: >
              pylint
              python3-dbus-client-gen
              python3-dbus-python-client-gen
              python3-psutil
              python3-pyudev
              python3-requests
              python3-semantic_version
              python3-pygithub
            image: fedora:32
            task: >
              (cd code_maintenance; make -f Makefile lint) &&
              (cd developer_tools; make -f Makefile lint) &&
              (cd tests/client-dbus; PYTHONPATH=./src make -f Makefile lint)
          - dependencies: black python3-isort
            image: fedora:32
            task: >
              (cd code_maintenance; make -f Makefile fmt-travis) &&
              (cd developer_tools; make -f Makefile fmt-travis) &&
              (cd tests/client-dbus; make -f Makefile fmt-travis)
          - dependencies: yamllint
            image: fedora:32
            task: make -f Makefile yamllint
          # MANDATORY PYTHON CHECKS ON LOWEST SUPPORTED INTERPRETER
          - dependencies: >
              pylint
              python3-dbus-client-gen
              python3-dbus-python-client-gen
              python3-psutil
              python3-pyudev
            image: fedora:29
            task: >
              (cd developer_tools; make -f Makefile lint) &&
              (cd tests/client-dbus; PYTHONPATH=./src make -f Makefile lint)
    runs-on: ubuntu-18.04
    container: ${{ matrix.image }}
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: >
          dnf install -y
          make
          python-unversioned-command
          ${{ matrix.dependencies }}
      - name: Display Python version
        run: python --version
      - name: Run test
        run: ${{ matrix.task }}
