---
name: stratisd nightly

# yamllint disable-line rule:truthy
on:
  schedule:
    - cron: 0 0 * * *

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  dependencies:
    runs-on: fedora:32
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          components: cargo
          toolchain: stable
      - name: Check for outdated dependencies
        run: make -f Makefile dependency_check
