---
name: stratisd nightly

# yamllint disable-line rule:truthy
on:
  schedule:
    - cron: 0 0 * * *

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  dependencies:
    runs-on: ubuntu-18.04
    container:
      image: fedora:32
      options: --privileged -v /dev:/dev
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies for Fedora
        run: >
          dnf install -y
          clang
          curl
          cryptsetup-devel
          dbus-devel
          libblkid-devel
          make
          python-requests
          python-semantic_version
          systemd-devel
      - uses: actions-rs/toolchain@v1
        with:
          components: cargo
          toolchain: stable
      - name: Check for outdated dependencies
        run: make -f Makefile compare-fedora
